name: real_estate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  page_view_indicator: ^2.0.2
  sliding_up_panel: ^0.3.6
  flutter_spinkit: ^4.1.1+1

  #logic
  image_picker: ^0.6.4
  firebase_database: ^3.1.1
  firebase_auth: ^0.15.3
  firebase_storage: ^3.1.5
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
